project:
  name: "test_project"
  chromosome: 'chr22'
  interval: 200000
  blackout:
    - [1, 60]

datasets:
  - name: "0 Hours"
    data: "ENCLB571GEP.chr22.200kb.h5.hic"
  - name: "12 Hours"
    data: "ENCLB870JCZ.chr22.200kb.12.h5.hic"

tracks:
  - name: "ATAC"
    file: "chr22.tracks.csv"
    columns:
      - name: "ATAC"
      - name: "ATAC"
        file: "chr22.tracks.12.csv"
  - name: "H3K27ac"
    file: "chr22.tracks.csv"
    columns:
      - name: "H3K27ac"
      - name: "H3K27ac"
        file: "chr22.tracks.12.csv"
  - name: "H3K9me3"
    file: "chr22.tracks.csv"
    columns:
      - name: "H3K9me3"
      - name: "H3K9me3"
        file: "chr22.tracks.12.csv"
  - name: "PC1"
    file: "chr22.tracks.csv"
    columns:
      - name: "PC1"
      - name: "PC1"
        file: "chr22.tracks.12.csv"
  - name: "PC2"
    file: "chr22.tracks.csv"
    columns:
      - name: "PC2"
      - name: "PC2"
        file: "chr22.tracks.12.csv"
