#
# Template for an example 4DGB Project
#

#
# Define main project settings here:
#
project:
  # Make a name for your project
  name: "example_project"
  # Select chromosome in Hi-C file to use
  chromosome: 'chr22'
  # Select bin resolution in Hi-C file to use
  interval: 200000
  # Only contacts with a value higher than this in the Hi-C
  # file will be used
  count_threshold: 2.0
  # FENE bond coefficient used in LAMMPS simulation:
  # If LAMMPS fails with a "bad FENE bond" error,
  # try increasing this value
  bond_coeff: 55
  # Hide a sequence of bins in the browser view.
  # The structure made from the example data
  # has a long "tail" at the start that we black-out
  blackout:
    - [1, 60]

#
# Define Datasets here:
# Each dataset has a name and a path to a Hi-C file
#
datasets:
  - name: "0 Hours"
    data: "ENCLB571GEP.chr22.200kb.h5.hic"
  - name: "12 Hours"
    data: "ENCLB870JCZ.chr22.200kb.12.h5.hic"

#
# Define data tracks here:
# The data for the second dataset is in a different file
# in this example, so you can see how the file is overriden
# for the second column in each dataset
#
tracks:
  # ATAC Data
  - name: "ATAC"
    file: "chr22.tracks.csv"
    columns:
      - name: "ATAC"
      - name: "ATAC"
        file: "chr22.tracks.12.csv"
  # H3K27ac Data
  - name: "H3K27ac"
    file: "chr22.tracks.csv"
    columns:
      - name: "H3K27ac"
      - name: "H3K27ac"
        file: "chr22.tracks.12.csv"
  # H3K9me3
  - name: "H3K9me3"
    file: "chr22.tracks.csv"
    columns:
      - name: "H3K9me3"
      - name: "H3K9me3"
        file: "chr22.tracks.12.csv"
  # PC1 Data
  - name: "PC1"
    file: "chr22.tracks.csv"
    columns:
      - name: "PC1"
      - name: "PC1"
        file: "chr22.tracks.12.csv"
  # PC2 Data
  - name: "PC2"
    file: "chr22.tracks.csv"
    columns:
      - name: "PC2"
      - name: "PC2"
        file: "chr22.tracks.12.csv"

#
# Include an annotation file here:
#
annotation:
  file: "chr22.gff"
  description: "Your description or citation here"

#
# Include "bookmarked" locations here.
# These will appear in the drop-down menus
# in the selection widget in the browser
#
bookmarks:
  # Favorite locations,
  # Defined as ranges of base-pairs
  locations:
    - [ 10600000, 28800000 ]
    - [ 28800000, 49000000 ]
  # Favorite genes
  # Defined as the names specified in the
  # annotation file
  genes:
    - "LOC105373060"
    - "LOC105372863"
    - "LOC107985541"
    - "LOC102724608"
