#!/bin/bash

read -r -d '' HELP<<'ENDHELP'
    run_project

    Start an instance of the 4DGB Browser for a project.

    Usage:
        ./run_project [-h|--help] [-|--port PORT] [-n|--name NAME] PROJECT_DIRECTORY

    Options:
        -h, --help:     View this help and exit
        -n, --name:     Set the name for the project
                        (defaults to the name of the project directory)
        -p, --port:     Set the port for the server to run on.
                        (default: 8000)

    Arguments:
        PROJECT_DIRECTORY:  Directory containing the project
                            (and workflow.yaml)
ENDHELP

# Reset IFS (newline, tab, space)
IFS='
     '
set -eu

PORT=8000
PROJECT=""
NAME_OVERRIDE=""

while [ "$#" -gt 0 ] ; do
    case "$1" in
        -h|--help)
            echo "$HELP"
            exit
            ;;
        -p|--port)
            shift
            PORT="$1"
            ;;
        -n|--name)
            shift
            NAME_OVERRIDE="yes"
            NAME="$1"
            ;;
        -*)
            echo "unrecognized option: $1"
            ;;
        *)
            PROJECT="$1"
            ;;
    esac
    shift
done

if [ -z "$PROJECT" ] ; then
    echo "No project specified." 1>&2
    echo "Usage: ./run_project [-|--port PORT] [-h|--help] PROJECT_DIRECTORY" 1>&2
    exit 1
fi

# Gotta define our own function because not all systems will have realpath(1) installed.
# Thanks, StackOverflow! https://stackoverflow.com/a/3915420/2827258
abspath() {
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

PROJECT="$(abspath "$PROJECT")"
if [ -z "$NAME_OVERRIDE" ] ; then
    NAME="$(basename "$PROJECT")"
fi

docker run --rm -it \
    -p "127.0.0.1:$PORT:80" \
    -v "$PROJECT:/project" \
    -e "NEWUID=$(id -u)" \
    -e "NEWGID=$(id -g)" \
    4dgb/workbench:latest "$PORT" "$NAME"
