project:
    name:       Project Name
    interval:   300 
    annotation: file.gff3
    blackout:   [0, 1]

sequence:
    name:       Thisname 
    data:       url.com 

datasets:
    - name:     This name 
      hic:      somefile.ext
      tracks:
        - name: one 
          data: somefile.yaml
        - name: two 
          data: somefile.yaml
    - name:     Another name 
      hic:      somefile.ext
      tracks:
        - name: one 
          data: somefile.yaml
        - name: two 
          data: somefile.yaml
