#!/usr/bin/env python3

import argparse
import textwrap
import yaml
import sys
import os

# ----------
# set up command line args
# ----------
desc = """A script that creates a 4D Genome Browser project from input data 
"""

parser = argparse.ArgumentParser(
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description=textwrap.dedent(desc)
                    )

parser.add_argument( '--destination',
                        default='./',
                        help='destination directory for new project')
parser.add_argument( '--workflow', 
                        default='workflow.yaml',
                        help='input workflow file')

args = parser.parse_args()

def get_project_directory(args):

    return os.path.join(args.destination, "this_new_name")

# read the input file
try:
    wyaml = open(args.workflow, 'r')
except FileNotFoundError:
    print("File \'{}\' not found. Aborting".format(args.workflow))
    sys.exit(1)
else:
    workflow = {}
    with open(args.workflow, 'r') as wyaml:
        workflow = yaml.load(wyaml, Loader=yaml.Loader)

    print("Loaded workflow \'{}\'.".format(args.workflow))
    newdir = get_project_directory(args)
    print(newdir)
    if not os.path.exists(newdir):
        os.makedirs(newdir)
    else:
        print("Directory already exists")

