# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: csv2tracks test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Run the csv2tracks test 
      run: |
        pip install numpy
        pip install pandas
        pip install pyyaml
        python -m unittest testing/test_csv2tracks.py
