# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 4DGBWorkflow create template test 

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Create the template and verify it
      run: |
        pip install checksumdir
        python -m unittest testing/test_template.py
